version: '3'
services:
  proxy_pool:
    image: jhao104/proxy_pool:2.4.0
    environment:
      - DB_CONN=redis://:password@redis:6379/0
    ports:
      - 5010:5010
  redis:
    image: redis
    command: redis-server --requirepass password